
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 18;
  public static final int READ = 8;
  public static final int NE = 25;
  public static final int LT = 21;
  public static final int OVER = 19;
  public static final int SEMICOLON = 13;
  public static final int ELSE = 4;
  public static final int PLUS = 16;
  public static final int RPAREN = 15;
  public static final int THEN = 3;
  public static final int END = 5;
  public static final int IF = 2;
  public static final int GT = 22;
  public static final int LPAREN = 14;
  public static final int LE = 23;
  public static final int WRITE = 9;
  public static final int ID = 10;
  public static final int NUM = 11;
  public static final int addop = 27;
  public static final int relop = 26;
  public static final int EOF = 0;
  public static final int GE = 24;
  public static final int MINUS = 17;
  public static final int error = 1;
  public static final int EQ = 20;
  public static final int UNTIL = 7;
  public static final int ASSIGN = 12;
  public static final int mulop = 28;
  public static final int REPEAT = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "REPEAT",
  "UNTIL",
  "READ",
  "WRITE",
  "ID",
  "NUM",
  "ASSIGN",
  "SEMICOLON",
  "LPAREN",
  "RPAREN",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "EQ",
  "LT",
  "GT",
  "LE",
  "GE",
  "NE",
  "relop",
  "addop",
  "mulop"
  };
}

